### ISSUE TITLE
multiple PCs and interpretation

### ISSUE THREAD

**Issue by larahurban** [rnowling/asaph#3]
Dear team,

Many thanks for providing this easy-to-use implementation of the inversion detection by PCA! 

I have an issue in that 'snp-association-tests --components 1 2 3 4 5' only gives me the output for the first PC. I downloaded the package last Friday. Are you aware of any bug that might cause this? 

I also attach my first result for PC1. May I ask you for your opinion since the signal here is not as clear as in the examples you provide: Would you assume that the upcoming thin peaks are signs of inversion, especially the one at the right (close to the vertical green line) that we would be interested in? 

![image](https://user-images.githubusercontent.com/11909495/82160792-e7af8e00-98eb-11ea-887c-ea83bd83e3c0.png)

Many thanks for your help in advance!

Best regards,
Lara

**Comment by rnowling** [comment]
Hi Lara,

Thanks for trying Asaph out!

Can you paste the commands you used?  I want to make sure that you calculated the PCA with more than 1 component, etc.  Can you also tell me what files are present in the `<workdir>/analysis/` directory?

Unfortunately, your plot is quite ambiguous.  There may be inversions, but I'm not confident.  Are you analyzing SNPs for a single chromosome?  Are you using samples from a single population?

Thanks!
